### ISSUE TITLE
Pagination feature broken

### ISSUE THREAD

**Issue by adamreger** [EmmaRamirez/spectrum#1]
When attempting to paginate through the data on the table, I get stuck after clicking on one of the pages

STR:
* Load App and scroll to bottom of table
* Validate that page values 1-4 are available
* Click on any of the page values
* Validate that you are displayed the data for the page that you selected, but the only pagination option available is "Previous". If you select "4" in the above step, validate that you have to click on "Previous" 3 times prior to the page numbers being shown again

**Comment by EmmaRamirez** [comment]
Pushing a fix for this now.
